# Generated by Django 5.2.3 on 2025-06-28 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GelirGider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tur",
                    models.CharField(
                        choices=[("gelir", "Gelir"), ("gider", "Gider")], max_length=10
                    ),
                ),
                ("tutar", models.DecimalField(decimal_places=2, max_digits=10)),
                ("aciklama", models.TextField(blank=True)),
                ("tarih", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Kullanici",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=50)),
                ("soyad", models.CharField(max_length=50)),
                ("eposta", models.EmailField(max_length=191, unique=True)),
                ("sifre", models.CharField(max_length=191)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("şef", "Şef"),
                            ("garson", "Garson"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yemek_adi", models.CharField(max_length=100)),
                ("fiyat", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Siparis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("masa_no", models.IntegerField()),
                ("toplam_tutar", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("bekliyor", "Bekliyor"),
                            ("hazırlanıyor", "Hazırlanıyor"),
                            ("hazır", "Hazır"),
                            ("teslim edildi", "Teslim Edildi"),
                        ],
                        default="bekliyor",
                        max_length=20,
                    ),
                ),
                ("tarih_saat", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stok",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("malzeme_adi", models.CharField(max_length=100)),
                (
                    "birim",
                    models.CharField(
                        choices=[
                            ("kg", "Kilogram"),
                            ("adet", "Adet"),
                            ("litre", "Litre"),
                        ],
                        max_length=10,
                    ),
                ),
                ("miktar", models.DecimalField(decimal_places=2, max_digits=10)),
                ("birim_fiyat", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Tarif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarif_adi", models.CharField(max_length=100)),
                ("aciklama", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Bildirim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mesaj", models.TextField()),
                (
                    "durum",
                    models.CharField(
                        choices=[("okunmadı", "Okunmadı"), ("okundu", "Okundu")],
                        default="okunmadı",
                        max_length=10,
                    ),
                ),
                ("tarih_saat", models.DateTimeField(auto_now_add=True)),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.kullanici",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiparisOgeleri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adet", models.PositiveIntegerField()),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.menu",
                    ),
                ),
                (
                    "siparis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.siparis",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="menu",
            name="tarif",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="restaurant.tarif",
            ),
        ),
        migrations.CreateModel(
            name="TarifMalzemesi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("miktar", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "stok",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.stok",
                    ),
                ),
                (
                    "tarif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.tarif",
                    ),
                ),
            ],
        ),
    ]
