# Generated by Django 5.2.3 on 2025-06-30 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kullanici",
            name="ad",
        ),
        migrations.RemoveField(
            model_name="kullanici",
            name="eposta",
        ),
        migrations.RemoveField(
            model_name="kullanici",
            name="sifre",
        ),
        migrations.RemoveField(
            model_name="kullanici",
            name="soyad",
        ),
        migrations.AlterField(
            model_name="bildirim",
            name="kullanici",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="kullanici",
            name="rol",
            field=models.CharField(
                choices=[("admin", "Admin"), ("sef", "Şef"), ("garson", "Garson")],
                default="garson",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("şef", "Şef"),
                            ("garson", "Garson"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
