# Generated by Django 5.2.3 on 2025-06-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurant",
            "0003_alter_kullanici_options_alter_kullanici_managers_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="kategori",
            field=models.CharField(
                choices=[
                    ("yemek", "Yemekler"),
                    ("sicak_icecek", "Sıcak İçecekler"),
                    ("soguk_icecek", "Soğuk İçecekler"),
                    ("tatli", "Tatlılar"),
                ],
                default="yemek",
                max_length=20,
            ),
        ),
    ]
