# Generated by Django 5.2.3 on 2025-07-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_menu_kategori"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bildirim",
            options={"verbose_name": "Bildirim", "verbose_name_plural": "Bildirimler"},
        ),
        migrations.AlterModelOptions(
            name="gelirgider",
            options={
                "verbose_name": "Gelir/Gider",
                "verbose_name_plural": "Gelir/Gider Kayıtları",
            },
        ),
        migrations.AlterModelOptions(
            name="kullanici",
            options={
                "verbose_name": "Kullanıcı",
                "verbose_name_plural": "Kullanıcılar",
            },
        ),
        migrations.AlterModelOptions(
            name="menu",
            options={"verbose_name": "Menü", "verbose_name_plural": "Menüler"},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profil", "verbose_name_plural": "Profiller"},
        ),
        migrations.AlterModelOptions(
            name="siparis",
            options={"verbose_name": "Sipariş", "verbose_name_plural": "Siparişler"},
        ),
        migrations.AlterModelOptions(
            name="siparisogeleri",
            options={
                "verbose_name": "Sipariş Öğesi",
                "verbose_name_plural": "Sipariş Öğeleri",
            },
        ),
        migrations.AlterModelOptions(
            name="stok",
            options={
                "verbose_name": "Stok Malzemesi",
                "verbose_name_plural": "Stok Malzemeleri",
            },
        ),
        migrations.AlterModelOptions(
            name="tarif",
            options={"verbose_name": "Tarif", "verbose_name_plural": "Tarifler"},
        ),
        migrations.AlterModelOptions(
            name="tarifmalzemesi",
            options={
                "verbose_name": "Tarif Malzemesi",
                "verbose_name_plural": "Tarif Malzemeleri",
            },
        ),
    ]
