# Generated by Django 5.2.3 on 2025-07-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0005_alter_bildirim_options_alter_gelirgider_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarifmalzemesi",
            name="birim",
            field=models.CharField(
                choices=[("kg", "Kilogram"), ("litre", "Litre"), ("adet", "Adet")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
