# Generated by Django 5.2.3 on 2025-07-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0006_tarifmalzemesi_birim"),
    ]

    operations = [
        migrations.AddField(
            model_name="siparis",
            name="odendi",
            field=models.BooleanField(default=False),
        ),
    ]
