# Generated by Django 5.2.3 on 2025-07-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0007_siparis_odendi"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Kategori",
                "verbose_name_plural": "Kategoriler",
            },
        ),
        migrations.AlterField(
            model_name="menu",
            name="kategori",
            field=models.CharField(
                choices=[
                    ("baslangic", "Başlangıç"),
                    ("anayemek", "Ana Yemke"),
                    ("tatli", "Tatlı"),
                    ("icecek", "İçecek"),
                ],
                default="yemek",
                max_length=20,
            ),
        ),
    ]
