# Generated by Django 5.2.3 on 2025-07-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0008_kategori_alter_menu_kategori"),
    ]

    operations = [
        migrations.CreateModel(
            name="Masa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numara", models.PositiveIntegerField(unique=True)),
                (
                    "durum",
                    models.CharField(
                        choices=[("bos", "Boş"), ("dolu", "Dolu")],
                        default="bos",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="stok",
            name="birim",
            field=models.CharField(
                choices=[
                    ("gr", "Gram"),
                    ("kg", "Kilogram"),
                    ("adet", "Adet"),
                    ("litre", "Litre"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="tarifmalzemesi",
            name="birim",
            field=models.CharField(
                choices=[
                    ("gr", "Gram"),
                    ("kg", "Kilogram"),
                    ("litre", "Litre"),
                    ("adet", "Adet"),
                ],
                max_length=10,
            ),
        ),
    ]
