# Generated by Django 5.2.3 on 2025-07-23 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0009_masa_alter_stok_birim_alter_tarifmalzemesi_birim"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="masa",
            options={"verbose_name": "Masa", "verbose_name_plural": "Masalar"},
        ),
        migrations.AddField(
            model_name="siparis",
            name="kullanici",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="siparisler",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="menu",
            name="kategori",
            field=models.CharField(
                choices=[
                    ("baslangic", "Başlangıç"),
                    ("anayemek", "Ana Yemek"),
                    ("tatli", "Tatlı"),
                    ("icecek", "İçecek"),
                ],
                default="yemek",
                max_length=20,
            ),
        ),
    ]
