# Generated by Django 5.2.3 on 2025-07-24 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0010_alter_masa_options_siparis_kullanici_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siparis",
            name="masa_no",
        ),
        migrations.AddField(
            model_name="siparis",
            name="masa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="siparisler_masa",
                to="restaurant.masa",
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="kategori",
            field=models.CharField(
                choices=[
                    ("baslangic", "Başlangıç"),
                    ("anayemek", "Ana Yemek"),
                    ("tatli", "Tatlı"),
                    ("salata", "Salata"),
                    ("icecek", "İçecek"),
                ],
                default="yemek",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="siparis",
            name="durum",
            field=models.CharField(
                choices=[
                    ("bekliyor", "Bekliyor"),
                    ("hazırlanıyor", "Hazırlanıyor"),
                    ("hazır", "Hazır"),
                    ("stok_yetersiz", "Stok Yetersiz "),
                    ("teslim_edildi", "Teslim Edildi"),
                    ("stok_yetersiz", "Stok Yetersiz"),
                    ("iptal_edildi", "İptal Edildi"),
                ],
                default="bekliyor",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="siparis",
            name="kullanici",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="siparisler_kullanici",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="siparis",
            name="toplam_tutar",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="siparisogeleri",
            name="siparis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ogeler",
                to="restaurant.siparis",
            ),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
